[package]
name = "guest-resource-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen = "0.31.0"

[lib]
crate-type = ["cdylib"]
